services:
  db:
    image: postgres:latest
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_DB: ginkstoriesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: user
      POSTGRES_ROOT_PASSWORD: root123
    
    volumes:
      - ./postgres-data/ginkstoriesdb/:/var/lib/postgresql/data/
    
    ports:
      - "5432:5432"